### ISSUE TITLE
[DESKTOP-landingpage] The ,,s`` letter from ''Alătură-te cauzei noastre și devino un contribuitor'' don't contains diacritics in blue navy section above the footer 

### ISSUE THREAD

**Issue by MariusD77** [peviitor-ro/search-engine#297]
## Precondition
URL: https://peviitor.ro
Browser: Chrome
Device: Acer Aspire 3
Platform: windows 11 Pro

### Step 1 <span style="color:#58b880"> **[Pass]** </span>
Open URL in browser

#### Expected Result
The website is loaded without any problem

### Step 2 <span style="color:#ff5538"> **[Fail]** </span>
Check the second text from the blue section, above the footer

#### Expected Result
The second text contains diacritics

**Comment by MariusD77** [comment]
[Open Defect in TestQuality](https://web.testquality.com/site/peviitor/project/12763?defectId=13807)

**Comment by AdiVanca** [comment]
The text no longer exists
