### ISSUE TITLE
[Deaktop-landingpage] The year in bottom sentence "© 2022 - Toate drepturile rezervate PE VIITOR" don't correspond with the actual year(2023)

### ISSUE THREAD

**Issue by MariusD77** [peviitor-ro/search-engine#299]
## Precondition
URL: https://peviitor.ro/
Device: HP 
Browser: Mozilla Firefox
Platform: Windows 10

### Step 1 <span style="color:#58b880"> **[Pass]** </span>
Open URL in browser.

#### Expected Result
Website is loaded without any issues.

### Step 2 <span style="color:#58b880"> **[Pass]** </span>
Scroll to footer.

#### Expected Result
Page is scrolled without any issues.

### Step 3 <span style="color:#ff5538"> **[Fail]** </span>
Inspect correctness of the text &quot;© 2022 - Toate drepturile rezervate PE VIITOR.&quot; .

#### Expected Result
The text should be&quot;© 2023 - Toate drepturile rezervate PE VIITOR.&quot; .

**Comment by MariusD77** [comment]
[Open Defect in TestQuality](https://web.testquality.com/site/peviitor/project/12763?defectId=13822)

**Comment by AdiVanca** [comment]
![bug1](https://github.com/peviitor-ro/search-engine/assets/72222644/398e56b3-5899-4112-a163-a42ac5c7d39b)
