### ISSUE TITLE
[MOBILE - landingpage] The "s" letter from ''Alătură-te cauzei noastre și devino un contribuitor'' doesn't contain diacritics in blue section above the footer

### ISSUE THREAD

**Issue by annamserban** [peviitor-ro/search-engine#301]
## Precondition
URL: https://peviitor.ro/
Device: Samsung A21s
Browser: Chrome

### Step 1 <span style="color:#58b880"> **[Pass]** </span>
Open URL in website.

#### Expected Result
Website is loaded without any issues.

### Step 2 <span style="color:#58b880"> **[Pass]** </span>
Scroll to blue section.

#### Expected Result
Page is scrolled without any issues.

### Step 3 <span style="color:#58b880"> **[Pass]** </span>
Check the text &quot;Dorești să ajuți alți oameni?&quot; in the blue section.

#### Expected Result
The text &quot;Dorești să ajuți alți oameni?&quot; has diacritics.

### Step 4 <span style="color:#ff5538"> **[Fail]** </span>
Check the text &quot;Alătură-te cauzei noastre si devino un contribuitor.&quot; in the blue section.

#### Expected Result
The text &quot;Alătură-te cauzei noastre si devino un contribuitor.&quot; is displayed in the blue section and has diacritics.

**Comment by annamserban** [comment]
[Open Defect in TestQuality](https://web.testquality.com/site/peviitor/project/12763?defectId=13838)

**Comment by AdiVanca** [comment]
There is no text "Dorești să ajuți alți oameni?"

**Comment by AdiVanca** [comment]
The text ''Alătură-te cauzei noastre și devino un contribuitor'' no longer exist
