### ISSUE TITLE
[MOBILE - landingpage] The year in the text "© 2022 - Toate drepturile rezervate PE VIITOR" doesn't correspond with the current one (2023)

### ISSUE THREAD

**Issue by annamserban** [peviitor-ro/search-engine#302]
Precondition

URL: https://peviitor.ro/
Device: Samsung A21s
Browser: Chrome

Steps to Reproduce:

Step 1 [Pass]

Open URL in browser.
Expected Result

Website is loaded without any issues.

Step 2 [Pass]

Scroll to footer.
Expected Result

Page is scrolled without any issues.

Step 3 [Fail]

Check if the year in the text "© 2022 - Toate drepturile rezervate PE VIITOR" is the current one (2023).
Expected Result

The year in the text "© 2022 - Toate drepturile rezervate PE VIITOR" corresponds with the current one (2023).

**Comment by AdiVanca** [comment]
After retesting, the year correspond with the current one (2024)
