### ISSUE TITLE
[Desktop-SERP] The year in the text "© 2022 - Toate drepturile rezervate PE VIITOR" doesn't match with the current year (2023)

### ISSUE THREAD

**Issue by adinacoste** [peviitor-ro/search-engine#307]
## Precondition
URL: https://peviitor.ro/
Device: Samsung Galaxy S21 Ultra 
Browser: Chrome
Platform: Android 12

### Step 1 <span style="color:#58b880"> **[Pass]** </span>
Open URL in browser

#### Expected Result
 The website is loaded without any error

### Step 2 <span style="color:#58b880"> **[Pass]** </span>
Click on &quot;Caută&quot;

#### Expected Result
The user is redirected to SERP

### Step 3 <span style="color:#58b880"> **[Pass]** </span>
Scroll down until reaching the footer

#### Expected Result
The footer is reached

### Step 4 <span style="color:#ff5538"> **[Fail]** </span>
Check the writing of &quot;© 2023 - Toate drepturile rezervate PE VIITOR&quot; 

#### Expected Result
The text is &quot;© 2023 - Toate drepturile rezervate PE VIITOR&quot;

**Comment by adinacoste** [comment]
[Open Defect in TestQuality](https://web.testquality.com/site/peviitor/project/12763?defectId=13881)

**Comment by AdiVanca** [comment]
Now the year in the text is made to appear automatically (20240
