### ISSUE TITLE
[DESKTOP - SERP] Clear search feature

### ISSUE THREAD

**Issue by exXhilarate** [peviitor-ro/search-engine#309]
As a user, a clear search feature would be very helpful. This should look like an "X" button on the far end of the search bar, which whenever clicked, would erase the whole content in the search bar. 

![image](https://user-images.githubusercontent.com/126906594/225339328-9b5152fe-f941-44cf-998b-462180609095.png)

**Comment by AdiVanca** [comment]
After implementation, the 'X' button in the search bar clears the search when the user clicks on it
