### ISSUE TITLE
[DESKTOP - SERP] County and country dropdown menus next to the search bar. 

### ISSUE THREAD

**Issue by exXhilarate** [peviitor-ro/search-engine#310]
**Is your feature request related to a problem? Please describe.**
Dropdown for location is incomplete.

**Describe the solution you'd like**
For a more complete UX, whenever the dropdown for location is clicked, instead of just a broad option to click (Romania), we need a more complex dropdown. This would include every county in Romania, alphabetically ordered from top to bottom. Furthermore, a separate dropdown for the country.

**Additional context**
![image](https://user-images.githubusercontent.com/126906594/225338632-c5dfce54-06e9-47f5-8b9d-2396702bd2e6.png)

**Comment by AdiVanca** [comment]
After typing a minimum of 3 letters in the location search bar, the user receives relevant suggestions such as city, county
