### ISSUE TITLE
[Desktop-SERP] The inserted input from the search bar is not cleared after user has pressed the ''Back'' button

### ISSUE THREAD

**Issue by adinacoste** [peviitor-ro/search-engine#311]
**ENVIRONMENT**: 
  - url: https://peviitor.ro/
  - browser: Google Chrome 

**STEPS TO REPRODUCE**: 
1. Access www.peviitor.ro 
2. Type an example of a job title(ex: developer).
3. Hit ''Enter'' button.
4. Inspect, developer jobs are displayed.
5. Click over the ''back'' button.
6. Inspect.

**EXPECTED RESULTS**: The search bar is cleared after user has pressed the ''Back'' button.

**ACTUAL RESULTS**: The inserted input from the search bar remains hanged after user has pressed the ''Back'' button.

Please have a look over the attached video:

https://user-images.githubusercontent.com/126108523/228340821-b4286fbc-d121-4f6b-a358-f4185f1d3ac2.mp4

**Comment by talidag** [comment]
Momentan ma ocup eu de acest ticket. Mersi!
