### ISSUE TITLE
Hover effect missing

### ISSUE THREAD

**Issue by sebiboga** [peviitor-ro/search-engine#339]
![image](https://github.com/peviitor-ro/ui-js/assets/41440889/8de7346e-b675-458f-ab63-a6dc620ca3b8)

**Comment by sebiboga** [comment]
Requirements: 
https://www.figma.com/file/gY6yYTFjC0fuZ4bTRlUaH6/Pe-viitor?type=design&node-id=804-141&mode=design

**Comment by sebiboga** [comment]
@lalalaurentiu feel free to assign bugs to any front-end team member... I just kept you as primary contact here

**Comment by lalalaurentiu** [comment]
All good
