### ISSUE TITLE
Dropdown should have same look and feel like in Figma design

### ISSUE THREAD

**Issue by sebiboga** [peviitor-ro/search-engine#340]
Requirements Figma Design:

https://www.figma.com/file/gY6yYTFjC0fuZ4bTRlUaH6/Pe-viitor?type=design&node-id=934%3A1599&mode=design&t=e0kCCQ21Fr5gUC9t-1

URL in test:
https://deluxe-monstera-f52db4.netlify.app/

**Comment by sebiboga** [comment]
@lalalaurentiu please use same look and feel like in our Figma Design

**Comment by lalalaurentiu** [comment]
done

**Comment by lalalaurentiu** [comment]
new test url [enviromen](https://peviitor.netlify.app)

**Comment by sebiboga** [comment]
QA PASS; thank you @lalalaurentiu
