### ISSUE TITLE
Add GitHUB logo that point to our issues for front-end

### ISSUE THREAD

**Issue by sebiboga** [peviitor-ro/search-engine#341]
We want to add GitHUB logo and add hyperlink to our front-end repo - Issues section
Users needs to be ABLE to file any BUG found in PROD

**Comment by sebiboga** [comment]
![github logo](https://github.com/peviitor-ro/ui-js/assets/41440889/eba31fea-81bf-4960-9199-876f52b5fc16)

**Comment by sebiboga** [comment]
current link to issues : https://github.com/peviitor-ro/ui-js/issues

**Comment by DianaDascalu2** [comment]
New current link to issues is https://github.com/peviitor-ro/search-engine/issues
