### ISSUE TITLE
Unique URL in SRP (Search Results Page)

### ISSUE THREAD

**Issue by sebiboga** [peviitor-ro/search-engine#363]
We need to have unique URL
For example, when opening this URL https://peviitor-ro.github.io/search-engine/rezultate?country=Rom%C3%A2nia&page=1 I should get results not 404

**Comment by sebiboga** [comment]
@lalalaurentiu this is still reproduging :(

![image](https://github.com/peviitor-ro/search-engine/assets/41440889/666c6af7-2d5c-4b36-8ec0-a6af8a636dce)

**Comment by lalalaurentiu** [comment]
Second attempt to rectify the issue #370 
I tested it on my GitHub page and on Netlify, and it works.
[GitHub Pages enviroment](https://lalalaurentiu.github.io/search-engine/)
[netlify enviroment](https://lustrous-kataifi-861bc2.netlify.app/)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by sebiboga** [comment]
validated.
