### ISSUE TITLE
Update link to point to our DISCORD community

### ISSUE THREAD

**Issue by sebiboga** [peviitor-ro/search-engine#367]
People have problems joining our Community therefore we need to help them jump much more quickly in our DISCORD
We will update the LINK from the "Alatura-te cauzei noastre" button on homepage to point to "https://discord.com/invite/t2aEdmR52a"
![image](https://github.com/peviitor-ro/search-engine/assets/41440889/1a074b42-a1c1-43ce-a65c-d7d9841e7c63)

**Comment by lalalaurentiu** [comment]
Done!
