### ISSUE TITLE
Jitsi meet to be added in the footer

### ISSUE THREAD

**Issue by sebiboga** [peviitor-ro/search-engine#374]
As a user I want to be able to enter the meeting real fast
A link in footer will help me

**Comment by lalalaurentiu** [comment]
Done! #379

**Comment by AdiVanca** [comment]
Link added in footer
![bug4](https://github.com/peviitor-ro/search-engine/assets/72222644/70a39fca-dbdb-4a7c-9baf-9668c2f69a03)
