### ISSUE TITLE
Alege Orase instead of Alege Localitatea

### ISSUE THREAD

**Issue by sebiboga** [peviitor-ro/search-engine#380]
Improper label "Orase" because in fact we are listing "Orase" and "Sate" which generically we can call them "Localitatea"
![image](https://github.com/peviitor-ro/search-engine/assets/41440889/8f385e7c-ccf8-49dc-ae69-c88c5e6f780d)

**Comment by lalalaurentiu** [comment]
Fixed! #381

**Comment by AdiVanca** [comment]
![bug3](https://github.com/peviitor-ro/search-engine/assets/72222644/789d5af0-6913-4973-a146-be15beb43034)
