### ISSUE TITLE
Ses - The number of jobs does not correspond

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/search-engine#383]
ENVIROMENT: production
COMPANY: Ses
URL 1: [Ses scrapers](https://scrapers.peviitor.ro/src/ses/)
URL 2:  [Ses peviitor](https://peviitor.ro/rezultate?q=ses&country=Rom%C3%A2nia&page=1)
Browser: Google Chrome
Device: laptop
OS: MacOS

Precondition:
The [site](https://peviitor.ro/) must be open in browser.

Steps:
Enter Ses in the search bar.
Click the button below the company logo.
Click the button Run Scraper.
Click See Jobs.

Expected results:
The number of jobs on [peviitor.ro](https://peviitor.ro/rezultate?q=ses&country=Rom%C3%A2nia&page=1) corresponds to the number of jobs from [Scrapers-UI](https://scrapers.peviitor.ro/src/ses/) 

Actual result:
The number of jobs on [peviitor.ro](https://peviitor.ro/rezultate?q=ses&country=Rom%C3%A2nia&page=1) does not correspond to the number of jobs from[Scrapers-UI](https://scrapers.peviitor.ro/src/ses/) 

<img width="1042" alt="Screenshot at Dec 07 17-52-33" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/fd02444d-abf0-4a41-9004-c2572e07e14f">
<img width="1290" alt="Screenshot at Dec 07 17-53-11" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/790c2ea5-b14e-4596-9c79-46d5d4bf6a3f">

**Comment by lalalaurentiu** [comment]
Fixed!
