### ISSUE TITLE
N-able - Number of job listings do not match the official website

### ISSUE THREAD

**Issue by iBixee** [peviitor-ro/search-engine#384]
COMPANY: N-able
URL: [N-able peviitor.ro](https://scrapers.peviitor.ro/src/n-able/index.html)
Company's Career website: [N-able official website](https://careers.n-able.com/jobs)
Browser: Google Chrome
Device: laptop
OS: MacOS

Precondition:
The [site](https://scrapers.peviitor.ro/src/n-able/index.html) must be open in browser.

Steps:

1. **Observe** number of job listings.
2. **Navigate** to and **click** the "See Jobs" button
3. Observe number of job listings

Expected results:
The job listing number should accurately reflect the information provided by the official website.

Actual result:
Discrepancies are observed in job listing number.

<img width="805" alt="Screenshot 2023-12-04 at 15 25 24" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/103507535/e6b16ff0-9754-47c8-b9db-a434a229bcf9">

<img width="817" alt="Screenshot 2023-12-04 at 15 25 49" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/103507535/5cbeb091-921e-4580-8916-b3a324e20746">

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdiVanca** [comment]
After retesting the  number of jobs is the same on scrapers, peviitor and on company website
![bug5](https://github.com/peviitor-ro/search-engine/assets/72222644/1d1f7b02-e085-4809-858c-f49086c8d4a0)
