### ISSUE TITLE
Eon - Different number of jobs on peviitor.ro(40) then the number of jobs on company website (37)

### ISSUE THREAD

**Issue by AdiVanca** [peviitor-ro/search-engine#385]
ENVIROMENT: production
URL: https://peviitor.ro/rezultate?q=eon&country=Rom%C3%A2nia&page=1
Browser: Chrome
Device: laptop
OS: Windows 10

STEPS TO REPRODUCE:
1) Open URL in browser
2) Check the number of jobs available for the company
3) Open the careers section of the company website
4) Check the number of jobs available
5) Compare it with the number of jobs from the URL

EXPECTED RESULTS:
The number of jobs posted on the URL https://peviitor.ro/rezultate?q=eon&country=Rom%C3%A2nia&page=1 should be the same like  the number of jobs posted on the company website on the careers section.

ACTUAL RESULTS:
The number of jobs posted on the URL https://peviitor.ro/rezultate?q=eon&country=Rom%C3%A2nia&page=1 is 40 and the number of jobs posted on the company website on the careers section is 37

![cap6](https://github.com/peviitor-ro/based_scraper_py/assets/72222644/d141b876-da86-4ea7-bf70-37c545997547)
![cap7](https://github.com/peviitor-ro/based_scraper_py/assets/72222644/12c7f89c-979f-4c5a-8a8e-49e6c74d43a0)

**Comment by lalalaurentiu** [comment]
Fixed!

**Comment by AdiVanca** [comment]
After retest the number of jobs on peviitor.ro is the same as the number of jobs on company website
