### ISSUE TITLE
The number of jobs is not updated after the required selection

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/search-engine#391]
**ENVIRONMENT**: Production
  - url: [peviitor.ro](https://peviitor.ro/) 
  - browser: Google Chrome

**STEPS TO REPRODUCE**: 
1. Enter url in browser [peviitor.ro](https://peviitor.ro/) 
2. Click pe location search bar.
3. Select "Toate"

**EXPECTED RESULTS**:
Above the search bar you can see the total number of jobs available on peviitor.ro

**ACTUAL RESULTS**:
The number of jobs is not updated after the required selection

https://github.com/peviitor-ro/search-engine/assets/137428958/e7f7774d-1e2e-439a-a1b1-421dae1afd7f

**Comment by robert-burcea** [comment]
https://github.com/peviitor-ro/search-engine/pull/402

**Comment by robert-burcea** [comment]
https://github.com/peviitor-ro/search-engine/pull/402
