### ISSUE TITLE
Adecco - The number of jobs from Scrapers-UI does not correspond with the jobs from the site peviitor.ro

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/search-engine#394]
ENVIROMENT: production
COMPANY: Adecco
URL 1: [Adecco Scrapers-UI](https://scrapers.peviitor.ro/src/superbet/)
URL 2: [Adecco peviitor.ro](https://peviitor.ro/rezultate?q=adecco&country=Rom%C3%A2nia&page=1)
Browser: Google Chrome
Device: laptop
OS: MacOS

Precondition:
The [site](https://peviitor.ro/) must be open in Google Chrome browser.

Steps:
1. Enter Adecco in the search bar.
2. Click the button below the company logo.
3. Click the button "Run Scraper".
4. Click the button "See jobs"

Expected results:
The number of jobs on [pe.viitor.ro](https://peviitor.ro/rezultate?q=adecco&country=Rom%C3%A2nia&page=1) corresponds to the number of jobs on [Scrapers-UI](https://scrapers.peviitor.ro/src/adecco/) 

Actual result:
The number of jobs on [pe.viitor.ro](https://peviitor.ro/rezultate?q=adecco&country=Rom%C3%A2nia&page=1) does not corresponds to the number of jobs on [Scrapers-UI](https://scrapers.peviitor.ro/src/adecco/) 

<img width="571" alt="Screenshot at Dec 13 13-31-55" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/fb84ba83-4ead-4dda-a507-099e9f0d6f7d">
<img width="817" alt="Screenshot at Dec 13 13-31-37" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/137428958/4c722b3b-94be-4d7a-a7f2-2122daac265d">

**Comment by lalalaurentiu** [comment]
Fixed!
