### ISSUE TITLE
KuehneNagel - Does not return results in a few scenarios

### ISSUE THREAD

**Issue by iBixee** [peviitor-ro/search-engine#395]
COMPANY: KuehneNagel
URL: [KuehneNagel peviitor.ro](https://scrapers.peviitor.ro/src/kuehne-nagel/index.html)
Company's Career website: [KuehneNagel official website](https://jobs.kuehne-nagel.com/global/en/search-results?qcountry=Romania)
Browser: Google Chrome
Device: laptop
OS: MacOS

Precondition:
The [site](https://www.peviitor.ro/) must be open in browser.

Steps:

1. **Type** "Kuehne-nagel/kuehne-nagelKuehne+nagel/kuehne+nagelKuehne Nagel/kuehne nagel/" in the search bar.
2. **Observe** the number of job listings on the page.

Expected results:
Results should be shown for each input at step 1.

Actual result:
Results are not shown for certain search bar inputs.

<img width="1378" alt="Screenshot 2023-11-27 at 14 32 16" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/103507535/e81c35f5-9457-4edb-98b3-ba5b6b38fd18">

<img width="1381" alt="Screenshot 2023-11-27 at 14 32 46" src="https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/103507535/47750841-1fe1-412d-bd45-92e2c2b8b7cc">

**Comment by CalinCatuta** [comment]
peviitor a primit Refactoring iar joburile unei firme se cauta prin drop-down bifand un check-box.
