### ISSUE TITLE
Remove Alatura-te from header

### ISSUE THREAD

**Issue by sebiboga** [peviitor-ro/search-engine#415]
The goal for 2024 is to build strong teams and we do not focus on new joiners anymore.
We will have on a middle of the screen so this Alatura-te button from header is no longer needed.

![image](https://github.com/peviitor-ro/search-engine/assets/41440889/ea31980c-43f9-4323-a960-7c95f4f0d5e2)

**Comment by AdiVanca** [comment]
![bug6](https://github.com/peviitor-ro/search-engine/assets/72222644/a0e94de2-2630-44f6-b9d3-bc007fbc06ba)
