### ISSUE TITLE
Adecco - GET 404 after refresh the page

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/search-engine#418]
ENVIROMENT: production
COMPANY: Adecco
URL: [Adecco peviitor.ro](https://peviitor.ro/rezultate?company=adecco&country=Rom%C3%A2nia&page=2)
Browser: Google Chrome
Device: phone
OS: Android

Precondition:
The [site](https://peviitor.ro/rezultate?company=adecco&country=Rom%C3%A2nia&page=2) must be open in Chrome browser.

Steps:
1. Click on the search bar from the second page from peviitor.ro
2. Write Adecco
3. Click on the "Cauta" button
4. Refresh the page.

Expected result:
When the page refreshes we receive a GET of 200 when we [inspect](https://peviitor.ro/rezultate?q=adecco&company=adecco&country=Rom%C3%A2nia&page=1) the page

Actual result:
When the page refreshes we receive a GET of 404 when we [inspect](https://peviitor.ro/rezultate?q=adecco&company=adecco&country=Rom%C3%A2nia&page=1) the page

https://github.com/peviitor-ro/Scrapers-UI/assets/137428958/ba1503a4-ff17-48b4-8ce1-ebc7992aa012

**Comment by lalalaurentiu** [comment]
why always me? 😄  Just kidding, I'll investigate

**Comment by AdelinaGuliman** [comment]
Mai dă-mi un exemplu de persoană care se ocupă și promit ca le împart în
două 😊

În mar., 16 ian. 2024 la 17:02 Baluta Laurentiu Marian <
***@***.***> a scris:

**Comment by lalalaurentiu** [comment]
> Mai dă-mi un exemplu de persoană care se ocupă și promit ca le împart în două 😊

Glumesc , am descoperit ca in query params se introduc q si company 
<img width="1065" alt="Screenshot 2024-01-16 at 17 09 08" src="https://github.com/peviitor-ro/search-engine/assets/67306273/0615c29b-cac9-4dd8-8f8c-deaa99b600a1">
Vreau sa vad daca problema asta e din ultimele commituri

**Comment by AdelinaGuliman** [comment]
Pe bune te întreb pe cine să mai asignez. Asta cu asignarea pe diferite
bug-uri încă e o nebuloasă pentru mine. Și app, chiar apreciez munca pe
care o depui pe acest proiect ✌🏻

În mar., 16 ian. 2024 la 17:11 Baluta Laurentiu Marian <
***@***.***> a scris:
