### ISSUE TITLE
Page delivered with ERROR CODE 404

### ISSUE THREAD

**Issue by sebiboga** [peviitor-ro/search-engine#420]
![image](https://github.com/peviitor-ro/search-engine/assets/41440889/d2bc2825-0456-4fd2-974c-22c8760e1270)

**Comment by CalinCatuta** [comment]
![image](https://github.com/peviitor-ro/search-engine/assets/77282302/d49b5ac0-0fd4-4ab2-93a5-ac7de0823b2b)
 
 Testul facut pe site-ul in productie. Response 200.
