### ISSUE TITLE
Longer letters are not displayed correctly in the search bar. The lower part of the letter is cut by whitespace

### ISSUE THREAD

**Issue by Sarra113** [peviitor-ro/search-engine#426]
**ENVIRONMENT**: 
  - url: https://peviitor.ro/
  - browser: Chrome
  - device: laptop
  - OS: Windows
  - Version: 10

**STEPS TO REPRODUCE**: 
1. Enter [url](https://peviitor.ro/) in browser
2. Type a longer letter in the search bar, for example - "g" or "j"

**EXPECTED RESULTS**:
The typed letter appears fully in the search bar.

**ACTUAL RESULTS**:
The lower part of the letter appears cut by whitespace.

![image](https://github.com/peviitor-ro/search-engine/assets/136991701/d81733cd-f1f5-441c-b0e8-1dd5c2afdfbb)

**Comment by copreapt** [comment]
Hi there!

It seems, the line height is too small, adding 2 extra pixels solves the issue.

![Screenshot 2024-01-23 010206](https://github.com/peviitor-ro/search-engine/assets/45538888/d3f2cb12-e205-4ae6-958f-5e332ee2de4e)

**Comment by CalinCatuta** [comment]
Problema a fost rezolvata.
