### ISSUE TITLE
Unresponsive back/forward button after performing searches in the main search bar 

### ISSUE THREAD

**Issue by ionutjbk** [peviitor-ro/search-engine#440]
**ENVIRONMENT**: 
  - URL: https://peviitor.ro/
  - Browser: Mozilla 
  - Device: laptop 
  - OS: Windows
  - Version: 10 

Pre-conditions: 
1: Peviitor.ro is up and running and you are located on the home page. 

**STEPS TO REPRODUCE**: 
1. Go to search bar, type a company name (example: google) and hit enter 
2. After the results are loaded search for another company and hit enter 
3. Click on the browser`s back button to navigate to previous page 
4. Click on the browser`s forward button 

**EXPECTED RESULTS**:
After performing multiple searches data is loaded in front end when using the browsers back or front button 

**ACTUAL RESULTS**:
No data is loaded after using the browsers back or front button 
The URL changes but no data is shown in the front end 

**Notes**: After clicking on back button, If you click in the URL box and hit enter, the data is loaded 

https://github.com/peviitor-ro/search-engine/assets/91414608/e8e89887-29b9-419e-aba5-b172499d3588

**Comment by talidag** [comment]
Momentan ma ocup eu de acest ticket. Multumesc!
