### ISSUE TITLE
Search bar not in focus after clicking on clear icon 

### ISSUE THREAD

**Issue by ionutjbk** [peviitor-ro/search-engine#442]
**ENVIRONMENT:**

URL: https://peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows
Version: 10

**Pre-conditions:**
1: Peviitor.ro is up and running

**STEPS TO REPRODUCE:**

1. Go to the search box and type a company name
2. Click on the clearing icon that`s is located on the far right of the input box 

**EXPECTED RESULTS:**

The text that is inside the input box should be cleared and focus is set inside 

**ACTUAL RESULTS:**

The text is cleared but the focus is not set 

https://github.com/peviitor-ro/search-engine/assets/91414608/849920ea-cbcf-40d0-b18e-401bc6ecff80

**Comment by CalinCatuta** [comment]
Asta nu este un Bug si nici o problema de cod. Verificati site-urile din prezent LinkedIn, Bestjobs si eJobs o sa vedeti ca sunt doua variante una este sa nu ai X acela iar alta este cum avem noi.
