### ISSUE TITLE
Hp- The scrapers.peviitor.ro doesn't recognize "Bucuresti" as a city for all the jobs

### ISSUE THREAD

**Issue by AdinaIT** [peviitor-ro/search-engine#445]
ENVIRONMENT: Production
URL: https://scrapers.peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Run scraper for "Hp" Company
3. Check location for all the (70) jobs

EXPECTED RESULTS:
On the scrapers.peviitor.ro the location for all (70) jobs is Bucuresti

ACTUAL RESULTS:
On the scrapers.peviitor.ro the location for all (70) jobs is "Bucharest". The scraper UI doesn't recognize "Bucuresti" as a city
On the https://peviitor.ro/ the location for all (70) jobs is "Bucuresti"
On the https://peviitor.ro/  if text location "Bucuresti, Bucuresti",  API doesn't return the jobs.  API return data only if the location is Romania.

Execute in SOLR   "fq":"city: \"Bucuresti\""  and  "fq":"city: \"Bucharest\"". The message is the same for both locations: "numFound":0"

![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/7444644e-d3f1-44e6-abca-c25e1662771c)

![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/37e61b08-ff35-44b5-b980-bdfd17dadf93)
![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/9f053ca4-9679-4faf-8ba9-0ae23ff8e285)

![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/f842a1eb-6b19-4b35-b8db-59794b1daa05)
![image](https://github.com/peviitor-ro/based_scraper_py/assets/127322865/65384f84-a9f8-41ac-8179-ecb7bde7b773)

**Comment by lalalaurentiu** [comment]
The county and city have changed in "Bucuresti", but the filter still does not work.The problem is on the filtering query

**Comment by robert-burcea** [comment]
I'm afraid I don't understand what the issue is, I find it working.

![Screenshot_2024-02-16-09-04-01-10_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/peviitor-ro/search-engine/assets/28507505/780d63dc-f958-4523-80f0-3d481510d804)

**Comment by robert-burcea** [comment]
For clarity purposes, the job card location should be "Bucuresti, Bucuresti", without any diacritics.

![Screenshot_2024-02-16-09-04-01-10_40deb401b9ffe8e1df2f1cc5ba480b12.jpg](https://github.com/peviitor-ro/search-engine/assets/28507505/780d63dc-f958-4523-80f0-3d481510d804)

**Comment by robert-burcea** [comment]
They have not changed to "Bucuresti", it still has diacritics.

![Screenshot_2024-02-16-10-15-33-48_8404db57de60b5d3d1c69008b20f5296.jpg](https://github.com/peviitor-ro/search-engine/assets/28507505/e5ab7011-470d-4dcc-9e25-70d23c2f42e8)

**Comment by AdinaIT** [comment]
Retesting:
- Run scraper for "hp" company . Validating the bug fix:  The scraper has recognize "Bucuresti" as a city and the number of jobs is the same as on as https://peviitor.ro/
- "Execute Query" in SOLR. "Bucuresti" it still has diacritics
- On the https://peviitor.ro/ "Bucuresti" it still has diacritics
- It'll be retested after the "validator" fixed correctly the location data for diacritics marks

![image](https://github.com/peviitor-ro/search-engine/assets/127322865/4c92c80d-b92c-48b5-829f-4c85cb8ce50b)
![image](https://github.com/peviitor-ro/search-engine/assets/127322865/f3914757-8a4e-4092-91fb-ba9e329a0a42)
![image](https://github.com/peviitor-ro/search-engine/assets/127322865/fba745f4-58ac-425d-93f2-d85a6dc7b975)

**Comment by CalinCatuta** [comment]
Sa se verifice acest Issues dupa ultimu update, ca sa primesti toate rezultatele din City cele cu diacritice sau fara trebuie folosit fuzzysearch in SOLR iar pe codul prezent in peviitor este actualizat.
