### ISSUE TITLE
Dell -  on the https://peviitor.ro missing  job type (Remote) for 3 of jobs 

### ISSUE THREAD

**Issue by AdinaIT** [peviitor-ro/search-engine#456]
ENVIRONMENT: Production
URL: https://peviitor.ro/
Browser: Chrome
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for "Dell" Company
3. Check the "type job" for the follow jobs: 
- Incident Response Consultant
- Software Senior Principal Engineer
- Senior Auditor (IT & Operations)

EXPECTED RESULTS:
On https://peviitor.ro the "Remote" job type is displayed for each of 3 mentioned jobs

ACTUAL RESULTS:
On https://peviitor.ro the scraper removed the "type job" (Remote) for that 3 jobs
On the solr.peviitor.ro the "type job" is displayed

![image](https://github.com/peviitor-ro/search-engine/assets/127322865/497bb4e8-9e41-45c8-8e54-efa513834f69)

![image](https://github.com/peviitor-ro/search-engine/assets/127322865/5a2e03ff-7d21-4c44-8621-c430dae25608)

![image](https://github.com/peviitor-ro/search-engine/assets/127322865/bca33003-b7d3-485f-8b4a-253e828997ba)

**Comment by CalinCatuta** [comment]
Am reparat eu, urmeaza sa pun codul in productie.
