### ISSUE TITLE
When remote feeds 'on-site' front shows 'remote'

### ISSUE THREAD

**Issue by robert-burcea** [peviitor-ro/search-engine#463]
**ENVIRONMENT**: 
  - url:  https://peviitor.ro/
  - browser:  chrome

**STEPS TO REPRODUCE**: 
1. enter peviitor.ro
2.  Search for 'casier' without introducing location (search in all Romania)

**EXPECTED RESULTS**:

Job location matches.

**ACTUAL RESULTS**:

For jobs that have 'on-site' for the 'remote', it shows 'remote', it should show the job's city

![remote-issue](https://github.com/peviitor-ro/search-engine/assets/28507505/a62bca89-65af-44b2-a3d6-bb29f24b7c22)
![remote-issue-2](https://github.com/peviitor-ro/search-engine/assets/28507505/ef9e1574-6ac6-47a3-9b76-14defe0e6de5)

**Comment by CalinCatuta** [comment]
https://github.com/peviitor-ro/search-engine/pull/465
