### ISSUE TITLE
LeroyMerlin - Location is missing on peviitor.ro

### ISSUE THREAD

**Issue by CristinaVoicu** [peviitor-ro/search-engine#469]
ENVIROMENT: production
URL: https://scrapers.peviitor.ro/src/leroymerlin/index.html
Company_careers_url: [LeroyMerlin](https://job.leroymerlin.ro/jobs)
Device: Laptop

OS: Windows 10 Pro 22H2
Browser: Google Chrome
Version: 122.0.6261.112

STEPS TO REPRODUCE:

1.Write "LeroyMerlin" in the search bar
2.Click on the company folder
3.Click on the "Run Scraper" button
4.Navigate to and click on the "See jobs" button
5.Observe the Location and compare the official website with the peviitor.ro page

EXPECTED RESULTS:
The Location from peviitor.ro, should accurately reflect the information provided by the official website.

ACTUAL RESULTS:
The Location is missing for 6 jobs, on peviitor.ro.

![Capture3](https://github.com/peviitor-ro/search-engine/assets/159782419/60f34851-f5a4-4b20-91a1-b518060d365e)
![Capture4](https://github.com/peviitor-ro/search-engine/assets/159782419/b1ca3af4-3f7a-4a19-b8bc-02a99f375f09)
![Capture5](https://github.com/peviitor-ro/search-engine/assets/159782419/b4d24a62-9648-4e7c-914e-90e792e3cd63)

![Capture6](https://github.com/peviitor-ro/search-engine/assets/159782419/28c013f0-511a-4a13-b218-012ca8d90bb1)
![Capture7](https://github.com/peviitor-ro/search-engine/assets/159782419/b00e8940-3e10-41eb-b6ab-28f0524673a5)
![Capture8](https://github.com/peviitor-ro/search-engine/assets/159782419/1216a038-e684-4383-b2b5-5272e42b3e6d)

![Capture9](https://github.com/peviitor-ro/search-engine/assets/159782419/8456e44c-155c-4ecd-a657-373d1eeeb4a8)
![Capture10](https://github.com/peviitor-ro/search-engine/assets/159782419/75dc9be4-86f6-448a-9c18-53542f6fbca0)
![Capture11](https://github.com/peviitor-ro/search-engine/assets/159782419/96df6cf0-0b1a-4a7c-8ca8-e838fc171628)

![Capture12](https://github.com/peviitor-ro/search-engine/assets/159782419/2fc92a55-dbe8-482c-90d2-ab3328eb8f2f)
![Capture13](https://github.com/peviitor-ro/search-engine/assets/159782419/ddc386cc-323f-4628-87b1-74cc53b5ece7)
![Capture14](https://github.com/peviitor-ro/search-engine/assets/159782419/0a1311d9-9783-43c3-b3f1-af4881666eed)

![Capture15](https://github.com/peviitor-ro/search-engine/assets/159782419/dd304bb1-4cdd-40e7-a76b-4cc8d4a16791)
![Capture16](https://github.com/peviitor-ro/search-engine/assets/159782419/f27669fb-4155-44e8-90b4-8e0e78cd9225)
![Capture17](https://github.com/peviitor-ro/search-engine/assets/159782419/58c0401a-9b1e-42bb-9230-082ecdaf9aa8)

![Capture18](https://github.com/peviitor-ro/search-engine/assets/159782419/0c13d996-2592-424c-bd75-876175715bc2)
![Capture19](https://github.com/peviitor-ro/search-engine/assets/159782419/e351c9b4-1d00-444a-8302-da55df2baba1)
![Capture20](https://github.com/peviitor-ro/search-engine/assets/159782419/ac57be41-94ec-4906-b17b-a19e94d10f69)

**Comment by CalinCatuta** [comment]
![image](https://github.com/peviitor-ro/search-engine/assets/77282302/8e065245-1338-48bd-90b3-2980b71892ed)
Va aparea pe ecran Hibrid pentru ca jobul este Hibrid cu tot ca exista si orasul Bucuresti. peviitor vom arata doar acel detaliu, daca user doreste informati mai multe va merge pe site-ul oficial al firmei.

**Comment by CristinaVoicu** [comment]
ok, multumesc de clarificari!
