### ISSUE TITLE
404 After refresh page

### ISSUE THREAD

**Issue by lalalaurentiu** [peviitor-ro/search-engine#483]
**ENVIRONMENT**: Production 
  - url: https://peviitor.ro
  - browser: safari mobile

**STEPS TO REPRODUCE**: 
1. enter url in browser
2. Click on search input
3. Write something
4. Wait response 
5. Click refresh page 

**EXPECTED RESULTS**:
Page must load with the same content

**ACTUAL RESULTS**:
Server returns 404
https://github.com/peviitor-ro/search-engine/assets/67306273/bf90b875-f49e-4c27-bcc9-6a17ecc8d843 404

**Comment by sebiboga** [comment]
![image](https://github.com/peviitor-ro/search-engine/assets/41440889/b2c6973a-82c0-43af-8adc-66b62a457019)

**Comment by sebiboga** [comment]
tocmai ma pregateam sa pun bug-ul asta... si vad ca a fost deja descoperit
good spot @lalalaurentiu

**Comment by CalinCatuta** [comment]
Sa facut modificare la cod https://github.com/peviitor-ro/search-engine/commit/a85b8d66e391c65b582864d48aa742a3497f3938
Problema era ca Router schimba Pagina complet.
