### ISSUE TITLE
Company logo and button are outside the card

### ISSUE THREAD

**Issue by lalalaurentiu** [peviitor-ro/search-engine#499]
**ENVIRONMENT**: 
  - url: [Peviitor](https://peviitor.ro)
  - browser: Safari Mobile

**STEPS TO REPRODUCE**: 
1. enter url in browser
2. search something

**EXPECTED RESULTS**:
The company logo and "Catre site" button must be in that card

**ACTUAL RESULTS**:
The company logo and button are outside the card. The button cannot be pressed
<img width="1440" alt="Screenshot 2024-04-15 at 11 42 51" src="https://github.com/peviitor-ro/search-engine/assets/67306273/e299a050-d6e2-406c-a627-beecdc5e44ec">

**Comment by CalinCatuta** [comment]
Viewport Size:
393px × 852px

Site-ul merge perfect pentru acel size si testat pe iPhone personal si in consola de la google.
Si daca ar exista problema ar fi strict pentru acel iPhone de la ceva anume si nu avem o rezolvare anume strict pentru el daca site-ul merge perfect pe celalante telefoane.

**Comment by lalalaurentiu** [comment]
> Viewport Size: 393px × 852px
> 
> Site-ul merge perfect pentru acel size si testat pe iPhone personal si in consola de la google. Si daca ar exista problema ar fi strict pentru acel iPhone de la ceva anume si nu avem o rezolvare anume strict pentru el daca site-ul merge perfect pe celalante telefoane. Poate exista o problema la ultimu ISO ptr acest iPhone si nu citeste ceva CSS comanda.

Și pe iPhone 11 aceiași problema

**Comment by CalinCatuta** [comment]
Cred ca e la toate iPhone care au acel 
![image](https://github.com/peviitor-ro/search-engine/assets/77282302/f4bc0581-7bf8-4f14-b96b-367cc274d818)

**Comment by CalinCatuta** [comment]
https://github.com/peviitor-ro/search-engine/commit/d529e21190a4cf988f87f8b238600f96b47e1627
