### ISSUE TITLE
for retrieving the companies please use v3/companies instead of v1/companies

### ISSUE THREAD

**Issue by sebiboga** [peviitor-ro/search-engine#501]
Hi @CalinCatuta 
We saw (me and @ale23yfm ) that you are calling v1/companies to retrieve the companies

We are going to update ALL v1 endpoints to get data from QA (test.peviitor.ro) environment
So, PROD one should be populated with v3 or v4 or v5 endpoints ONLY

Please update the call to companies to get the data from v3/companies

Thanks.

**Comment by CalinCatuta** [comment]
https://github.com/peviitor-ro/search-engine/commit/ef3b6d8dd91756e68bf01e7d7bf5e630a95c61bf
