### ISSUE TITLE
Verify if the "Cauta" button is functional

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/search-engine#545]
Description:
When the user types a job he can find it after he press the "Cauta" button.

Precondition: 
The [website](https://peviitor.ro/) is up and running

**Comment by AdelinaGuliman** [comment]
> **Step 1**
Type in the search bar a name of a job

**Expected results** 
The name of the job appears in the search-bar

**Comment by AdelinaGuliman** [comment]
> **Step 2**
Press the "Cauta" button

**Expected result** 
Another page opens containing the named job.

**Comment by gabim060** [comment]
I tested the functionality of the "Cauta" button and it works properly.
