### ISSUE TITLE
The Bearingpoint company is duplicated when you filter by Companie

### ISSUE THREAD

**Issue by cornel13** [peviitor-ro/search-engine#556]
ENVIRONMENT:

url: https://peviitor.ro/#/rezultate
browser: chrome
STEPS TO REPRODUCE:

enter url in browser
tap on Companie and write Bearingpoint 

EXPECTED RESULTS:
The Bearingpoint should be visible and the user can select it

ACTUAL RESULTS:
The Bearingpoint company is duplicated

ATTACHEMENTS:
![Bearingpoint_duplicate_name](https://github.com/peviitor-ro/search-engine/assets/49681058/6ced0d42-0f5d-4610-9177-0ff883857848)

**Comment by lalalaurentiu** [comment]
Fixed

**Comment by cornel13** [comment]
Closing the ticket as the issue has been fixed.
