### ISSUE TITLE
Check if you press the "pe viitor" button, go back to the home page

### ISSUE THREAD

**Issue by yonutzu** [peviitor-ro/search-engine#589]
Description:
The customer can go back to homepage by pressing the "pe viitor" button

Precondition
The website https://peviitor.ro/ is up and running

**Comment by yonutzu** [comment]
> **Step 1**
The user press the "Cauta" button

Expected result
A new page is open

**Comment by yonutzu** [comment]
> **Step 2**
The user press the "Pe viitor" button

Expected result
Pressing "Pe viitor" button, user will return at the homepage

![Image](https://github.com/user-attachments/assets/8f604e31-8a0b-42d2-8753-bfeae0d4ae08)

**Comment by Lore78** [comment]
[(laptop - Chrome and Firefox), (tableta - Android), (telefon - Android)]
