### ISSUE TITLE
Verify that the "pe viitor" button refreshes the page

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/search-engine#594]
Description:
The customer can refresh the page by pressing the "pe viitor" button.

Precondition:
The [website](https://peviitor.ro/) is up and running

**Comment by AdelinaGuliman** [comment]
> **Step 1**
Click the "pe viitor" button

**Expected result** 
The page refreshes

**Comment by Lore78** [comment]
[(laptop - Chrome and Firefox), (tablet - Android), (telephone - Android)
