### ISSUE TITLE
 The page shows more position results but displays fewer.

### ISSUE THREAD

**Issue by talmacelanamaria** [peviitor-ro/search-engine#608]
ENVIROMENT: production
URL: https://peviitor.ro/
**Company_careers_url**: Asociatia de Oportunitati si Cariere
 Desktop:public

OS: 
Browser:Chrome
Version: 
A

 
### **STEPS TO REPRODUCE:**
1) Go on https://peviitor.ro/#/rezultate
2) Search" casier " at job 
3) Put the filter "Brasov" at "Oras" 

>**EXPECTED RESULTS:**
1)The page must display all jobs by filter "casier"  from the city selected  and all companies available.

>**ACTUAL RESULTS:**
1) The page shows more position results  but displays fewer.
<>

**Screenshots**
![Captură de ecran 2024-07-12 161449](https://github.com/user-attachments/assets/a0d91778-de1e-4ff6-aaa3-bb6ff127912d)

**Comment by talmacelanamaria** [comment]
in the meantime it was resolved.

**Comment by lalalaurentiu** [comment]
close issues if resolved.

**Comment by talmacelanamaria** [comment]
Done
