### ISSUE TITLE
The page display just two companies even if you selected more companies from checkbox . 

### ISSUE THREAD

**Issue by talmacelanamaria** [peviitor-ro/search-engine#621]
ENVIROMENT: production
URL: https://peviitor.ro/
**Company_careers_url**: A CUT ABOVE SRL
 Desktop:Chrome
A
OS: 
Browser:Chrome
Version: 
A

 
### **STEPS TO REPRODUCE:**
1) Go On https://peviitor.ro/#/rezultate
2)Search "Casier"and Sfantu Gheorghe city
3) Select more company from chechbox 

>**EXPECTED RESULTS:**
When selected more companies the page must display just those companies.

>**ACTUAL RESULTS:**
The page display just two companies even if you selected more companies from checkbox . 
<>

**Screenshots**
![Captură de ecran 2024-07-09 094243](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/161446018/d9008ff6-a1df-4f5c-8fd6-fb76f94e333f)
![Captură de ecran 2024-07-09 094307](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/161446018/f6124c32-1fd3-43d6-bf78-37a378013cd9)

**Comment by lalalaurentiu** [comment]
Fixed...
