### ISSUE TITLE
The post "Casier " on page is added twice at same company.

### ISSUE THREAD

**Issue by talmacelanamaria** [peviitor-ro/search-engine#622]
ENVIROMENT: production
URL: https://peviitor.ro/
**Company_careers_url**: U.S. Food Network S.A.
 Desktop:public

OS: 
Browser:Chrome
Version: 
A

 
### **STEPS TO REPRODUCE:**
1) Go on https://peviitor.ro/#/rezultate
2) Search by "CASIER" and Sfantu Gheorghe 

>**EXPECTED RESULTS:**
1) The page must display  correct after filters added.

>**ACTUAL RESULTS:**
1)The post "Casier " on page is added twice at same company.
<>

**Screenshots**
![Captură de ecran 2024-07-11 192854](https://github.com/peviitor-ro/Scrapers_Cristi_Olteanu/assets/161446018/47595fac-b911-44a7-8513-51f8382e6bd2)

**Comment by lalalaurentiu** [comment]
It's not duplicate, jobs have different ids
![image](https://github.com/user-attachments/assets/39061bce-2693-4e7f-85dd-d2909a6a0531)
![image](https://github.com/user-attachments/assets/0690ab80-cade-4523-9419-e3a1a61809a3)
