### ISSUE TITLE
[mobile] Responsive design: Different IT company logos haven't the same size!

### ISSUE THREAD

**Issue by CarmenSteliana** [peviitor-ro/search-engine#661]
ENVIRONMENT
url: https://peviitor.ro/
browser: Safari
operating system: iOS
version: 17.5.1

STEPS TO REPRODUCE:

   1. open the url in Safari
   2. write "QA" in the "Cauta un loc de munca" input
   3. click on the "Cauta" button

EXPECTED RESULTS: Every IT company logo should have the same size. 
ACTUAL RESULTS: There is no uniformity. Some logos are smaller and some larger.

![logo1](https://github.com/user-attachments/assets/b0675b57-2e5e-4e46-b0d0-a29039981d94)
![logo2](https://github.com/user-attachments/assets/f078aafb-967d-4af8-90d0-3230c298b0e1)
![logo3](https://github.com/user-attachments/assets/52e22967-04fd-43c7-93e2-937fb6412558)

**Comment by catiboc** [comment]
Tested on OPERA -- this issue is reproducing here also
