### ISSUE TITLE
The selected company after refresh doesn't match

### ISSUE THREAD

**Issue by catiboc** [peviitor-ro/search-engine#670]
**ENVIRONMENT**: 
  - url: https://peviitor.ro/#/rezultate
  - browser: Opera

**STEPS TO REPRODUCE**: 
1. enter url in browser
2. Type "reparator incaltaminte" in search bar
3. Select "ABC International srl" in "companie" 
4. A list with 6 jobs appear

![image](https://github.com/user-attachments/assets/9f8b2d07-3295-40bc-aef7-a659cc0e6084)
5. Click on "pe viitor" and go back to the main page
6. The search bar is empty
7. Type "cofetar"
8. The "companie" was selected from the previous search and doesn't reseted (I expected to reset)

**EXPECTED RESULTS**:
Some new jobs to the same company appears or the company filter reseted

**ACTUAL RESULTS**:
A lot of jobs from other companies appears, just the job title matches, nothing else
There 44 results
![image](https://github.com/user-attachments/assets/a1e677b6-66e4-444a-9b50-6e9f7f999ab1)

**Comment by CalinCatuta** [comment]
@lalalaurentiu  cred ca nu mai exista bugul asta acum.

**Comment by lalalaurentiu** [comment]
@CalinCatuta nu mai e
