### ISSUE TITLE
The number of jobs from the main page and the second page doesn't match . It was created bug #583 in Chrome

### ISSUE THREAD

**Issue by catiboc** [peviitor-ro/search-engine#672]
**ENVIRONMENT**: 
  - url: peviitor.ro/#/rezultate
  - browser: Opera

**STEPS TO REPRODUCE**: 
1. enter url in browser
2. The main page has displayed one number of jobs
![image](https://github.com/user-attachments/assets/5dd46741-1c4a-4509-a5e6-e9e731be27db)
3.The second page has displayed another number of jobs
![image](https://github.com/user-attachments/assets/718a6dc0-b3c7-43d2-a5ec-fd92ac2bb523)

**EXPECTED RESULTS**:
The two numbers would be the same or if something makes these  two numbers inequal , a message with a reason appears

**ACTUAL RESULTS**:
The second page has displayed another number of jobs than the main page
![image](https://github.com/user-attachments/assets/65212c4c-ed22-49a1-82a5-dd71d0953f27)

**Comment by CalinCatuta** [comment]
Numarul este diferit pentru ca unul arata cate joburi sau bagat in DB iar celalant arata cate afisam din DB.
