### ISSUE TITLE
[laptop: Firefox] Typo in the "Mod de lucru" filter - no diacritics for "La fata locului"

### ISSUE THREAD

**Issue by Lore78** [peviitor-ro/search-engine#678]
**ENVIRONMENT**: 
  - url: https://peviitor.ro/#/rezultate
  - browser: Firefox
  - operating system: Windows 11 Home
  - version: 23H2

**STEPS TO REPRODUCE**: 
1. Go to https://peviitor.ro/#/rezultate
2. Filter by "Mod de lucru".
3. Check that there are free options available.

**EXPECTED RESULTS**:
When filtering by "Mod de lucru", the options "La fața locului", "Hibrid" și "La distanță" should be displayed.

**ACTUAL RESULTS**:
When filtering by "Mod de lucru", there is a typo: "La fata locului" instead of "La fața locului".

![image](https://github.com/user-attachments/assets/5e51015b-0c97-45e4-a6a6-b381284ad8de)

**Comment by CalinCatuta** [comment]
https://github.com/peviitor-ro/search-engine/pull/691
