### ISSUE TITLE
Not all the "RWS" jobs are available 

### ISSUE THREAD

**Issue by catiboc** [peviitor-ro/search-engine#684]
**ENVIRONMENT**: 
  - url: https://peviitor.ro/#/rezultate
  - browser: Opera

**STEPS TO REPRODUCE**: 
1. enter url in browser
2. Select any job
3. Select "Rws" company , press "cauta"
4. Appear 10 results
5. Click on each "Catre site"

**EXPECTED RESULTS**:
For each result you can see the job conditions

**ACTUAL RESULTS**:
There are just 6 available jobs
This page appears if you choose : Project Administrator Cluj-Napoca, BI & Data Product Analyst Cluj-Napoca ,Java Developer LC Cluj-Napoca, Java Developer Cluj-Napoca
![image](https://github.com/user-attachments/assets/cc1dadf8-29ba-40c6-a15c-78ef23d8649e)

**Comment by CalinCatuta** [comment]
Nu este un bug pe site-ul nostru, jobul a fost sters de pe site-ul oficial iar noi nu le stergem de pe site momentan.
