### ISSUE TITLE
"Romstal" jobs numbers are different on "peviitor-ro" and the "Romstal" own page

### ISSUE THREAD

**Issue by catiboc** [peviitor-ro/search-engine#686]
**ENVIRONMENT**: 
  - url: https://peviitor.ro/#/rezultate
  - browser: Opera

**STEPS TO REPRODUCE**: 
1. enter url in browser
2. Search for any job title
3. Select "Romastal" company
4. There are 68 results
![image](https://github.com/user-attachments/assets/533c7814-db2f-4113-aebb-8fe16b136be2)

5. Open https://cariere.romstal.ro/search/, "Romstal' own page for jobs.
6. There are 7 results
![image](https://github.com/user-attachments/assets/8616573e-677d-45cb-a3ae-429e2f7bed19)

**EXPECTED RESULTS**:
The number of results have to be same

**ACTUAL RESULTS**:
There are different numbers of results between the two pages

**Comment by catiboc** [comment]
This issue is reproducing at "Rompetrol" also. The number of result makes the difference, 36 on "peviitor.ro" and 24 on pe "Rompetrol" own page.
![image](https://github.com/user-attachments/assets/246f7b9d-b9ce-4006-aafa-a8954d7f9a12)
![image](https://github.com/user-attachments/assets/b9679126-3b70-4fea-917f-aa90e2455691)

**Comment by CalinCatuta** [comment]
Joburile pe site-ul oficial se inchid pentur ca au gasit angajati pe acel post dar peviitor jobul ramane in DB, nu se poate schimba nimic pana nu va exista in Back-end o metoda sa se stearga joburi dupa un anumit timp.
