### ISSUE TITLE
After a company was selected the search button skip to the beginning of the list

### ISSUE THREAD

**Issue by catiboc** [peviitor-ro/search-engine#687]
**ENVIRONMENT**: 
  - url: https://peviitor.ro/#/rezultate
  - browser: Opera

**STEPS TO REPRODUCE**: 
1. enter url in browser
2. No job selected
3. A company was selected
4. The results appear
5. You want to choose another company

**EXPECTED RESULTS**:
You can deselect or not the previous company from the list and choose another one

**ACTUAL RESULTS**:
You can't deselect from the list 
![image](https://github.com/user-attachments/assets/e7f731ca-1487-4a7b-817f-79e71ead5f7e)
 because the list skip to the beginning, you can deselect  just from the "Sterge filtre"

**Comment by CalinCatuta** [comment]
Se poate selecta si deselecta in drop-down.
Daca un User bifeaza un element si inchide drop-down atunci va sterge elementu bifat din sectiunea cu taguri apasand pe X sau 
"Sterge filtre" pentru a sterge toate filtrele asta este UX gandit si implementant.
