### ISSUE TITLE
[laptop: Firefox] Error 404 on searching the "Functionar administrativ" position from Lugera - Ghimbav

### ISSUE THREAD

**Issue by Lore78** [peviitor-ro/search-engine#688]
**ENVIRONMENT**: 
  - url: https://peviitor.ro/#/rezultate
  - browser: Firefox
  - operating system: Windows 11 Home
  - version: 23H2

**STEPS TO REPRODUCE**: 
1. Go to https://peviitor.ro/#/rezultate
2. Search by "functionar administrativ".
3. Check the response from Lugera - Ghimbav.

**EXPECTED RESULTS**:
When searching the "functionar administrativ" position from Lugera Ghimbav, the respective position should be displayed with all the details. 

**ACTUAL RESULTS**:
When searching the "functionar administrativ" position from Lugera Ghimbav, the "404 Nu a fost găsit" error appears on the screen. 

![image](https://github.com/user-attachments/assets/90a8938e-5f1a-4f14-a568-b74049663dc8)

![image](https://github.com/user-attachments/assets/4ad3d398-7b25-4022-b796-a53ddd26aa2e)

**Comment by CalinCatuta** [comment]
404 este pe pagina firmei unde era jobul, nu este un Bug pe site-ul nostru.
Apare 404 pentru ca au sters jobu.
