### ISSUE TITLE
[laptop: Firefox] "ASOCIAȚIA OPORTUNITĂȚI ȘI CARIERE" at the bottom of the main page is written without diacritics

### ISSUE THREAD

**Issue by Lore78** [peviitor-ro/search-engine#689]
**ENVIRONMENT**: 
  - url: https://peviitor.ro/#/rezultate
  - browser: Firefox
  - operating system: Windows 11 Home
  - version: 23H2

**STEPS TO REPRODUCE**: 
1. Go to https://peviitor.ro/#/rezultate
2. Check the main page.
3. Check that the name of the association is written correctly. 

**EXPECTED RESULTS**:
ASOCIAȚIA OPORTUNITĂȚI ȘI CARIERE at the bottom of the page should be written with diacritics. 

**ACTUAL RESULTS**:
ASOCIAȚIA OPORTUNITĂȚI ȘI CARIERE at the bottom of the page is not written with diacritics. 

![image](https://github.com/user-attachments/assets/144f6815-5b79-42a7-b1c8-d415027554c8)

**Comment by CalinCatuta** [comment]
https://github.com/peviitor-ro/search-engine/pull/690
