### ISSUE TITLE
[laptop: Firefox] Companies having diacritics in the name are not taken into consideration by "Companie" filter

### ISSUE THREAD

**Issue by Lore78** [peviitor-ro/search-engine#704]
ENVIRONMENT:

- url: https://peviitor.ro/#/rezultate
- browser: Firefox
- operating system: Windows 11 Home
- version: 23H2

STEPS TO REPRODUCE:

1. Go to https://peviitor.ro/#/rezultate
2. Open the "Companie" filter.
3. Introduce a company that includes diacritics in their name and check the results.

EXPECTED RESULTS:
When introducing a company name that includes diacritics, the system should return the jobs/number of jobs listed by the respective company.

ACTUAL RESULTS:
When introducing a company name that includes diacritics, the system returns all the jobs/number of jobs on the site.

![image](https://github.com/user-attachments/assets/45bcba60-8150-4d8b-abce-80e1d2946c13)

![image](https://github.com/user-attachments/assets/605d3b09-d613-4e04-ac91-24c7241da68b)

![image](https://github.com/user-attachments/assets/7c20245c-b46c-4518-aa48-e108dac7750d)

**Comment by lalalaurentiu** [comment]
Iar problema diacriticelor 😂. Bun, lăsând gluma la o parte vedem ce stabilim dacă le mai păstrăm sau nu. Cauzează foarte multe probleme. Din ultima ședință au zis ca le păstrează doar pentru orașe.
