### ISSUE TITLE
Page freezes on company name filter

### ISSUE THREAD

**Issue by RaresCode** [peviitor-ro/search-engine#709]
**ENVIRONMENT**: 
  - url: https://peviitor.ro/
  - browser: Brave

**STEPS TO REPRODUCE**: 
1. Enter url in browser
2. Press on "Cauta" button
3. Press on "Companie" button 

**EXPECTED RESULTS**: The page remains responsive after clicking the "Companie" button and company names are displayed promptly.
**ACTUAL RESULTS**: The Page freezes and company names take too long to load.
![image](https://github.com/user-attachments/assets/0f6e60fa-5074-423f-9f73-78141a4e3f5f)

**Comment by CalinCatuta** [comment]
@RaresCode sa rezolvat codul pe BE si nu mai exista problema.
