### ISSUE TITLE
The icon linkedIn is accesible but the view is half in portrait on mobile

### ISSUE THREAD

**Issue by talmacelanamaria** [peviitor-ro/search-engine#716]
**ENVIRONMENT**: 
  - url: https://peviitor.ro/
  - browser: Chrome
  - device: mobile Huawei P30 Lite 

**STEPS TO REPRODUCE**: 
1. Go on https://peviitor.ro/
2. Verify the screen size on page 
3. Verify the size 's icons 

**EXPECTED RESULTS**:
1. The icons  must be clear and accessible in portrait and landscape format.

**ACTUAL RESULTS**:
1. The icon linkedIn is accesible but the view is half in portrait on mobile .
![Screenshot_20240729_133512_com android chrome (1)](https://github.com/user-attachments/assets/d8cd8275-13c5-4dbf-a644-9f3e0cbb7700)

**Comment by CalinCatuta** [comment]
Bug-ul apare pe telefoane cu ecran mai mic de 410px.

**Comment by CalinCatuta** [comment]
Rezolvat.
https://github.com/peviitor-ro/search-engine/pull/732
