### ISSUE TITLE
[laptop-Firefox] All job adds from FIS (23) lead to Page not found error

### ISSUE THREAD

**Issue by Lore78** [peviitor-ro/search-engine#719]
ENVIRONMENT

- url: https://peviitor.ro/
- browser: Firefox
- operating system: Windows 11 Home
- version: 23H2

STEPS TO REPRODUCE:

1. Go to https://peviitor.ro/#/rezultate
2. Type "Fis" in the "Companie" filter bar.
3. Check the jobs found.

EXPECTED RESULTS:
The job adds from FIS should lead to available jobs/web pages.

ACTUAL RESULTS:
The 23 job ads from FIS lead to the error "The page you are looking for doesn't exist".

https://fis.wd5.myworkdayjobs.com/SearchJobs/job/ROM-BUCH-224-Virtual/Java-Software-Engineer-Specialist--Worldpay-_JR0267002/

https://fis.wd5.myworkdayjobs.com/SearchJobs/job/ROM-BUCH-224-Virtual/Talent-Acquisition-Sourcer---12-Month-Fixed-Term-Contract_JR0273018/

https://fis.wd5.myworkdayjobs.com/SearchJobs/job/ROM-BUCH-224-Virtual/QA-Software-Tester_JR0267396/

https://fis.wd5.myworkdayjobs.com/SearchJobs/job/ROM-BUCH-224-Virtual/Java-Software-Engineer-Specialist_JR0267321/

https://fis.wd5.myworkdayjobs.com/SearchJobs/job/ROM-BUCH-224-Virtual/QA-Software-Tester_JR0267395/

https://fis.wd5.myworkdayjobs.com/SearchJobs/job/ROM-BUCH-224-Virtual/Quality-Assurance-Analyst-II--Worldpay-_JR0267025/

**Comment by Lore78** [comment]
The same bug reproduces on tablet-Chrome.

**Comment by CalinCatuta** [comment]
Sa se verifice iar Bug-ul pentru ca sau facut modificari pe BE.
![image](https://github.com/user-attachments/assets/480c9124-99cc-42d4-8ef5-6cee4376596a)
@Lore78
