### ISSUE TITLE
Test search with single keyword and leading/trailing spaces

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/search-engine#722]
Description:
The job search engine correctly handles searches with a single keyword that includes leading and trailing spaces, ensuring it returns the same results as the keyword without spaces.

Precondition: 
The [website](https://peviitor.ro/) is up and running.

**Comment by AdelinaGuliman** [comment]
> **Step 1**
Type the keyword " Engineer " into the search bar, including leading and trailing spaces

**Expected result** 
The search engine ignore leading and trailing spaces

**Comment by AdelinaGuliman** [comment]
> **Step 2**
Click the "Cauta" button

**Expected result** 
The search results for " Engineer " is identical to the search results for "Engineer."

**Comment by AdelinaGuliman** [comment]
> **Step 3**
Observe the search results returned.

**Expected result** 
The search engine returns relevant job listings for the keyword "Engineer."

**Comment by Lore78** [comment]
[laptop - Windows 11 - Chrome and Firefox] [telephone - Android - Chrome] [tablet - Android - Chrome]
