### ISSUE TITLE
Check the Search Bar Functionality in Incognito or Private Browsing Mode in Opera Browser

### ISSUE THREAD

**Issue by Lore78** [peviitor-ro/search-engine#745]
Description: The search bar works in incognito or private browsing mode in Opera browser.
Preconditions: The [website](https://peviitor.ro/) is up and running.

**Comment by Lore78** [comment]
>**Step 1**
1. Enter a search term in the search bar.

*Expected results*
1. The job name appears in the search bar.

**Comment by catiboc** [comment]
The search bar functionality works well in both browsing: in Incognito or in Opera Browser
