### ISSUE TITLE
Check that short query is allowed in search bar 

### ISSUE THREAD

**Issue by talmacelanamaria** [peviitor-ro/search-engine#769]
Description 
The short query is accepted 

Precondition 
The [website](https://peviitor.ro/#/rezultate) is up and running

**Comment by talmacelanamaria** [comment]
> **Step 1**
Click on checkbox and write " Gasesc un contabil ?"

**Expected result** 
The short query is allowed in box.

**Comment by talmacelanamaria** [comment]
> **Step 2**
Click on "Cauta " button 

**Expected result** 
The  new information display on page.

**Comment by Lore78** [comment]
[laptop - Windows 11 - Chrome and Firefox] [tablet - Android - Chrome] [telephone - Android - Chrome]
