### ISSUE TITLE
Check that search bar works with Firefox browser

### ISSUE THREAD

**Issue by talmacelanamaria** [peviitor-ro/search-engine#774]
Description 
The search bar  is functional on Firefox browser

Precondition 
The [website](https://peviitor.ro/) is up and running

**Comment by talmacelanamaria** [comment]
> **Step 1**
Click on checkbox and write " Economist "

**Expected result** 
The text in search bar is accepted and the browser works.

**Comment by talmacelanamaria** [comment]
> **Step 2**
Click on " Cauta " button 

**Expected result** 
The new page with information opens.

**Comment by AlexandruFBN** [comment]
buna! s au facut/repartizat cazurile de testare? as dori pt weeknd sa am
cateva sa testez :)

În lun., 19 aug. 2024 la 19:40, Guliman Adelina-Ioana <
***@***.***> a scris:
