### ISSUE TITLE
Check that users can paste the text in field

### ISSUE THREAD

**Issue by talmacelanamaria** [peviitor-ro/search-engine#777]
Description 
The users can paste the text complex in field 

Precondition
The [website](https://peviitor.ro/#/rezultate) is up and running

**Comment by talmacelanamaria** [comment]
> **Step 1**
Click on field and write " Inginer de calitate "

**Expected result** 
The field accepted the text pasted.

**Comment by talmacelanamaria** [comment]
> **Step 2**
Click on " Cauta" button 

**Expected result** 
The page is running correctly.

**Comment by talmacelanamaria** [comment]
> **Step 3**
3. Delete the words "Inginer de calitate "

**Expected result** 
The words are deleting with success.

**Comment by Lore78** [comment]
[laptop -  Windows 11 - Chrome and Firefox] [telephone - Android - Chrome]  [tablet - Android - Chrome]
