### ISSUE TITLE
Check that functional when the connection is lost

### ISSUE THREAD

**Issue by talmacelanamaria** [peviitor-ro/search-engine#778]
Description 
The page is  not functional without connection

Precondition 
The [website](https://peviitor.ro/)  is not functional when the connection is lost.

**Comment by talmacelanamaria** [comment]
> **Step 1**
Click in checkbox and write " Secretara "

**Expected result** 
The name of job is accepted .

**Comment by talmacelanamaria** [comment]
> **Step 2**
Disconnect from the internet

**Expected result** 
The name of  the job  remains  in box and the number total of jobs not appears.

**Comment by talmacelanamaria** [comment]
> **Step 3**
Click on " Cauta " button 

**Expected result** 
The new page  opens with information but the of companies display jerky

**Comment by talmacelanamaria** [comment]
> **Step 4**
Connect the internet 

**Expected result** 
The page continues to functional with dates introducing

**Comment by Lore78** [comment]
[laptop - Windows 11 - Chrome and Firefox] [tablet - Android - Chrome] [telephone - Android - Chrome]
