### ISSUE TITLE
Check that functional when the connection is lost and the users can continue their search when connection is enabled again

### ISSUE THREAD

**Issue by talmacelanamaria** [peviitor-ro/search-engine#779]
Description 
The users can  return on first page when the connection is enabled again

Precondition 
 The [website](https://peviitor.ro/) is up and running

**Comment by talmacelanamaria** [comment]
> **Step 1**
Click on checkbox and write " Casier"

**Expected result** 
The text is agreed with connection.

**Comment by talmacelanamaria** [comment]
> **Step 2**
Click on " Cauta " button 

**Expected result** 
The new page is open about jobs.

**Comment by talmacelanamaria** [comment]
> **Step 3**
Disconnect from the internet

**Expected result** 
The " Cauta " button is not functional on page

**Comment by talmacelanamaria** [comment]
> **Step 4**
 Click to go back on page 

**Expected result** 
The sign is functional and the page return on first page.

**Comment by talmacelanamaria** [comment]
> **Step 5**
Write  the text " Merchandiser" 

**Expected result** 
The text is accepted .

**Comment by talmacelanamaria** [comment]
> **Step 6**
Click on "Cauta" button 

**Expected result** 
The new page  opens .

**Comment by talmacelanamaria** [comment]
> **Step 7**
Connect the internet 

**Expected result** 
The checkbox is empty.

**Comment by Lore78** [comment]
[laptop - Windows 11 - Chrome and Firefox] [tablet - Android - Chrome] [telephone - Android - Chrome]
