### ISSUE TITLE
After the selection of multiples locations, the "Sterge filtre" button appears

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/search-engine#789]
Description
The user can see the "Sterge filtre" button next to the filters and above the results

Precondition
The [website](https://peviitor.ro/#/rezultate) is up and running

**Comment by AdelinaGuliman** [comment]
> **Step 1**
Flick on page and press on  icons in landscape mode .

**Expected result** 
The  view of page is complete in landscape mode and the icons are accessible.

**Comment by CarmenSteliana** [comment]
> **Step 2**
Click on "Oras" button

**Expected result** 
The drop down box opens

**Comment by CarmenSteliana** [comment]
> **Step 3**
Select all the cities from the list

**Expected result** 
Click on all the company checkboxes, the "Sterge filtre" button appears next to the filters and above the results
