### ISSUE TITLE
The existence of the "X" button for each city selected

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/search-engine#811]
Description
The customer can see the "X"  near the city name

Precondition
The [website](https://peviitor.ro/) is up and running

**Comment by AdelinaGuliman** [comment]
Step 1
Click the "Cauta" button

Expected result
The [results page](https://peviitor.ro/#/rezultate) opens

**Comment by catiboc** [comment]
> **Step 2**
Click on "Oras" button

**Expected result** 
The  drop down box opens

**Comment by catiboc** [comment]
> **Step 3**
Select a city from the list or insert the fisrt letters of the city name and select it

**Expected result** 
The selected city is marked with a tick in green box and the city name appears near the "sterge filtre" in a light green spot with an "X"
