### ISSUE TITLE
The text from the drop-down menu is not perfectly framed

### ISSUE THREAD

**Issue by AdelinaGuliman** [peviitor-ro/search-engine#821]
ENVIROMENT: Production
URL: [peviitor.ro](https://peviitor.ro/)
Browser: Chrome
Device: Laptop
OS: MacOS

Precondition:
The [website](https://peviitor.ro/#/rezultate?page=1) is up and running

STEPS TO REPRODUCE:
1. Click "Companie" button
2. Scroll down in the drop-down menu

EXPECTED RESULTS:
The text from the drop-down menu is perfectly framed when the user scrolls down

ACTUAL RESULT:
The text from the drop-down menu is not perfectly framed when the user scrolls down

https://github.com/user-attachments/assets/b87e2c72-f085-4f9b-9351-aec4fc01e6d5

**Comment by CalinCatuta** [comment]
@AdelinaGuliman  acest Issues este vechi iar site-ul a avut schimbari de cod din Scss in TailwindCss asa ca acest Issues nu este valid in prezent.
