### ISSUE TITLE
[laptop] No results if a city is entered in the search bar and another is selected from the dropdown menu!

### ISSUE THREAD

**Issue by CarmenSteliana** [peviitor-ro/search-engine#832]
ENVIROMENT: Production
URL: [peviitor.ro](https://peviitor.ro/)
Browser: Firefox
Device: Laptop
OS: Windows 11

Precondition:
The [website](https://peviitor.ro/) is up and running

STEPS TO REPRODUCE:
1. Open the URL in Firefox broswer
2. Type in the search bar "Cluj Napoca"
3 Select București from the dropdown "Oraș"

EXPECTED RESULTS: The jobs that are in both locations should appear
ACTUAL RESULT:  Ops! Cautarea nu are rezultat

![no jobs](https://github.com/user-attachments/assets/a1dd34f4-7294-4b4b-aa0b-675e5de4e2a8)
![jobs filtering](https://github.com/user-attachments/assets/fa621876-bc0f-4a9a-82df-447e6bcb27cd)

**Comment by lalalaurentiu** [comment]
De ce ai scris în căutare Cluj și ai aplicat pe orașe București? El încearcă să găsească jobul "Cluj-Napoca" situat în București. Nu are logică

**Comment by lalalaurentiu** [comment]
Dacă vrei să se aplice pentru ambele orașe selectează-le din filtrul de orașe

**Comment by CarmenSteliana** [comment]
Cu alte orase precum: Timisoara, Brasov, merge. Imi da joburile care sunt in ambele locatii.

**Comment by lalalaurentiu** [comment]
Celelate au locația trecută în numele jobului

**Comment by CarmenSteliana** [comment]
Da, dar sunt si multe fara si filtreaza corect
![Timisoara-Cluj Napoca jobs](https://github.com/user-attachments/assets/5c587ca0-399c-44c9-9ab1-19ea1388cc75)

**Comment by CalinCatuta** [comment]
![image](https://github.com/user-attachments/assets/d522c723-5735-4e4a-ba84-d02baba0cdf3)
Filtru pentru Orasul Bucuresti a fost rezolvat.
Iar acest Test nu este unul Valid pentru ca simularea ar face acest lucru: job_title:Cluj-Napoca si oras:Bucuresti si acest lucru nu exista pentru nu sunt joburi in Bucuresti cu numele Cluj-Napoca iar acest lucru nu este un UX posibil pentru User pentru ca el stie ca acel Input este pentru Titlu Jobului nu pentru a scrie un nume de Oras, pentru asta exista acel drop-down de orase.
