### ISSUE TITLE
(UX) Filter "Oras" - for city names that are longer and use 2 lines - should enter on one line only

### ISSUE THREAD

**Issue by Luvnrj** [peviitor-ro/search-engine#835]
On dropdown menu for Filter "Oras" for some city names, the name is dividing on two lines (see attached photo).
It would look better if the entire city name would enter on a single line.

![enhoras](https://github.com/user-attachments/assets/e8e6f020-0c34-4012-9d4c-7ee462bb1240)

**Comment by CalinCatuta** [comment]
![image](https://github.com/user-attachments/assets/b483dc88-1afc-41c0-996c-e0530c3ab60c)
Proiectul a trecut pe TailwindCss si problema a fost rezolvata.
