### ISSUE TITLE
Make the navbar be the full width of the screen as in Figma design (LANDING PAGE)

### ISSUE THREAD

**Issue by talidag** [peviitor-ro/search-engine#859]
![image](https://github.com/user-attachments/assets/ee281592-10b7-4e42-8454-ea2cb42859dd)
![image](https://github.com/user-attachments/assets/90c7ee63-de6e-4897-af83-cca8d3327823)

**Comment by Niki2222** [comment]
It will be done another UI for the search bar on Landing page.
