### ISSUE TITLE
Folositi diacritice

### ISSUE THREAD

**Issue by sebiboga** [peviitor-ro/search-engine#875]
![image](https://github.com/user-attachments/assets/19b5aa69-ad26-4a0c-ac5c-e3fd5e1ea690)

**Comment by AdelinaMoroaca** [comment]
I've corrected the spelling for the buttons:
![image](https://github.com/user-attachments/assets/ce62a907-aea2-494e-8eda-56dd5e1390ce)
![image](https://github.com/user-attachments/assets/2a795424-df5d-48e3-8dad-1c513fed1ec2)
