### ISSUE TITLE
Results component should be consistently left-aligned

### ISSUE THREAD

**Issue by AdelinaMoroaca** [peviitor-ro/search-engine#879]
The "Cities Results" section should be consistently left-aligned across all screen sizes. Screens smaller than 1024px need to be adjusted for left alignment as well.

**EXPECTED RESULTS**:
![image](https://github.com/user-attachments/assets/0a727c86-ab9a-43c0-afa5-0506c362fdae)

**ACTUAL RESULTS**:
![image](https://github.com/user-attachments/assets/85349034-80a5-4c63-9eda-4c23111019b4)

![image](https://github.com/user-attachments/assets/ea24135c-0c05-4f6d-852c-a862ad6596f7)

**Comment by Niki2222** [comment]
Issue solved.
