### ISSUE TITLE
Improve main page styling

### ISSUE THREAD

**Issue by AdelinaMoroaca** [peviitor-ro/search-engine#881]
Header and search-bar size:

**EXPECTED RESULTS** for header: Header and footer lines should be similar.
Please resize the header line to match the footer.
![image](https://github.com/user-attachments/assets/a8c8953b-1e86-4824-80ef-29035afd13ba)

The search bar width-size does not match the expected design.
This is the expected design:
![image](https://github.com/user-attachments/assets/dbe1f3e8-3297-4243-9f21-637a1b08c604)
This is the actual search bar:
![image](https://github.com/user-attachments/assets/851a5d25-5061-4833-bd54-4ed5fda68532)

**Comment by Niki2222** [comment]
Issue solved.
