### ISSUE TITLE
Button text not centered for search button

### ISSUE THREAD

**Issue by AndreiBarari** [peviitor-ro/search-engine#887]
**ENVIRONMENT**: 
  - url: https:
https://peviitor.ro
https://peviitor.ro/#/rezultate?page=1
  - browser: Chrome

**STEPS TO REPRODUCE**: 
1. enter urls in browser

**EXPECTED RESULTS**:
The text in search button should be centered

**ACTUAL RESULTS**:
The text in search button on both pages, home and rezultate is not horizontally aligned

**Comment by AdelinaMoroaca** [comment]
Centered text buttons and adjust border radius
