### ISSUE TITLE
Fix page navigation

### ISSUE THREAD

**Issue by AdelinaMoroaca** [peviitor-ro/search-engine#892]
when user navigates to a new page, that one should start from top 

**ACTUAL RESULTS**:
when user is on the buttom of the page and search for job/presses "Cauta" button
![image](https://github.com/user-attachments/assets/b828705d-87b4-4135-80f3-9c8255aa9a8b)

the next page view is on the same level as the previous one :
![image](https://github.com/user-attachments/assets/240c77fb-b143-45ea-9795-27cbccb64ea4)

**EXPECTED RESULTS**:
![image](https://github.com/user-attachments/assets/d03cab79-0b08-445e-bb8f-9ea406085795)

**Comment by Niki2222** [comment]
Issue solved.
